name: classgraph
description: 
version: 1.0.0
author: zhouweixian <laxian2010@qq.com>
homepage: https://github.com/laxian/dart-classgraph


environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  args: ^1.5.1
  path: ^1.6.2

dev_dependencies:
  analyzer: ^0.34.0
  test: ^1.5.1+1